version: '3.8'
services:
  db:
    image: postgres:15
    env_file:
      - api/.env.example
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: ./api
    env_file:
      - api/.env.example
    ports:
      - '4000:4000'
    depends_on: [db]
    volumes:
      - ./api/uploads:/usr/src/app/uploads
  web:
    build: ./web
    env_file:
      - web/.env
    ports:
      - '3000:80'
    depends_on: [api]
volumes:
  db_data:
