services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_pass
      POSTGRES_DB: productos_db
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: tu_pass
      DB_NAME: productos_db
      JWT_SECRET: secreto123
      PORT: 4000
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - ./api/uploads:/usr/src/app/uploads

  web:
    build: ./web
    environment:
      - REACT_APP_API_URL=http://tudominio.com/api
    ports:
      - '80:80'
    depends_on:
      - api

volumes:
  db_data:s